[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"
  FLASK_APP = "run.py"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
